export const WON_GAME_MESSAGE = 'WON_GAME_MESSAGE';
export const PRIZE_AWARDED_MESSAGE = 'PRIZE_AWARDED_MESSAGE';
export const TEESA_WALLET_INSUFFICIENT_FUNDS_MESSAGE = 'TEESA_WALLET_INSUFFICIENT_FUNDS_MESSAGE';