export const cases = [
  { secretWord: 'dog', message: 'Could it be a cat?', guess: 'cat', isCorrect: false },
  { secretWord: 'dog', message: 'I bet it\'s a horse.', guess: 'horse', isCorrect: false },
  { secretWord: 'dog', message: 'I guess the word is dog?', guess: 'dog', isCorrect: true },
  { secretWord: 'phone', message: 'Could it be a computer?', guess: 'computer', isCorrect: false },
  { secretWord: 'phone', message: 'Maybe a tablet?', guess: 'tablet', isCorrect: false },
  { secretWord: 'phone', message: 'Is the word telephone?', guess: 'telephone', isCorrect: true },
  { secretWord: 'game', message: 'Could it be a toy?', guess: 'toy', isCorrect: false },
  { secretWord: 'game', message: 'The word is game.', guess: 'game', isCorrect: true },
  { secretWord: 'color', message: 'Could the answer be paint?', guess: 'paint', isCorrect: false },
  { secretWord: 'color', message: 'I bet the secret word is colour.', guess: 'colour', isCorrect: true },
  { secretWord: 'house', message: 'What about an apartment complex?', guess: 'apartment complex', isCorrect: false },
  { secretWord: 'house', message: 'The secret word must surely be house.', guess: 'house', isCorrect: true },
  { secretWord: 'time', message: 'Is it clock?', guess: 'clock', isCorrect: false },
  { secretWord: 'time', message: 'Could it be a day?', guess: 'day', isCorrect: false },
  { secretWord: 'time', message: 'The answer must be time.', guess: 'time', isCorrect: true },
  { secretWord: 'rain', message: 'Could it perhaps be snow?', guess: 'snow', isCorrect: false },
  { secretWord: 'rain', message: 'I think it\'s a cloud, maybe?', guess: 'cloud', isCorrect: false },
  { secretWord: 'rain', message: 'Hmm, I suspect it is probably rain.', guess: 'rain', isCorrect: true },
  { secretWord: 'bat', message: 'I think it might be a ball?', guess: 'ball', isCorrect: false },
  { secretWord: 'bat', message: 'Could it be a vampire?', guess: 'vampire', isCorrect: false },
  { secretWord: 'bat', message: 'Could the word be bat?', guess: 'bat', isCorrect: true },
  { secretWord: 'doctor', message: 'Could it be a nurse?', guess: 'nurse', isCorrect: false },
  { secretWord: 'doctor', message: 'I wonder if it\'s a surgeon?', guess: 'surgeon', isCorrect: false },
  { secretWord: 'doctor', message: 'It has to be a doctor.', guess: 'doctor', isCorrect: true },
  { secretWord: 'foot', message: 'Could I guess hand?', guess: 'hand', isCorrect: false },
  { secretWord: 'foot', message: 'Probably toe?', guess: 'toe', isCorrect: false },
  { secretWord: 'foot', message: 'After thinking long and hard, I bet the answer is feet!', guess: 'feet', isCorrect: true },
  { secretWord: 'cafe', message: 'Could it be a restaurant?', guess: 'restaurant', isCorrect: false },
  { secretWord: 'cafe', message: 'I am quite sure the answer is café.', guess: 'café', isCorrect: true },
  { secretWord: 'pizza', message: 'Is it pasta?', guess: 'pasta', isCorrect: false },
  { secretWord: 'pizza', message: 'Could it be bread?', guess: 'bread', isCorrect: false },
  { secretWord: 'pizza', message: 'Is it... pizza!?', guess: 'pizza', isCorrect: true }
];