import { expect } from 'chai';
import { describe, it } from 'mocha';
import { isMessageGuess } from '../src/get-message-type';

const cases = [
  { input: 'I think it might be a boat', expected: true },
  { input: 'Maybe it is a cat', expected: true },
  { input: 'it is fish', expected: true },
  { input: 'it is a bird', expected: true },
  { input: 'I think it might be something with wheels', expected: false },
  { input: 'does it have wheels?', expected: false },
  { input: 'car', expected: true },
  { input: 'hello there', expected: false },
  { input: 'How many letters?', expected: false },
  { input: 'Is it any ot these: dog, cat, bat', expected: false },
  { input: 'I think it’s a car', expected: true },
  { input: 'dog!', expected: true },
  { input: 'Tell me about cars', expected: false },
  { input: 'children', expected: true },
  { input: 'cats', expected: true },
  { input: '  куче  ', expected: false },
  { input: '¿es un avión?', expected: false },
  { input: 'café', expected: true },
  { input: 'running', expected: false },
  { input: '123', expected: false },
  { input: 'Is it big or small?', expected: false },
  { input: 'What color is it?', expected: false },
  { input: 'is it spelled W-I-N-D?', expected: false },
  { input: 'how many letters?', expected: false },
  { input: 'Is it an animal?', expected: false },
  { input: 'Can it fly?', expected: false },
  { input: 'Does it make a sound?', expected: false },
  { input: 'Is it edible?', expected: false },
  { input: 'Can you hold it?', expected: false },
  { input: 'Is it bigger than a breadbox?', expected: false },
  { input: 'Does it grow?', expected: false },
  { input: 'Is it not a plant?', expected: false },
  { input: 'Could it be found outdoors?', expected: false },
  { input: 'Would you say it is man-made?', expected: false },
  { input: 'Is the answer related to food?', expected: false },
  { input: 'Heavy?', expected: false },
  { input: 'Is the word I am thinking of "book"?', expected: true },
  { input: 'Does its name contain the letter E?', expected: false },
  { input: 'does it have wheels?', expected: false },
  { input: 'is it used for transportation?', expected: false },
  { input: 'is it alive?', expected: false },
  { input: 'hello there, I was wondering if you could tell me more about this game', expected: false },
  { input: 'What about those NFTs?', expected: false },
  { input: 'How am I doing till the moment?', expected: false },
  { input: 'What do we know about the word so far?', expected: false },
  { input: 'I think it\'s a bicycle', expected: true },
  { input: 'is it alive', expected: false },
  { input: 'is it an animal?', expected: false },
  { input: 'is it heavier than 100 kg?', expected: false },
  { input: 'Could it be a cat?', expected: true },
  { input: 'I bet it\'s a horse.', expected: true },
  { input: 'I guess the word is dog?', expected: true },
  { input: 'do people have it in their houses?', expected: false },
  { input: 'is it running on electricity?', expected: false },
  { input: 'is it made entirely from metal?', expected: false },
  { input: 'Could it be a computer?', expected: true },
  { input: 'Maybe a tablet?', expected: true },
  { input: 'Is the word telephone?', expected: true },
  { input: 'is it interesting?', expected: false },
  { input: 'Can you eat it?', expected: false },
  { input: 'Could it be a toy?', expected: true },
  { input: 'Is it a sport?', expected: false }, 
  { input: 'The word is game.', expected: true },
  { input: 'is it something you can touch?', expected: false },
  { input: 'is it related to vision', expected: false },
  { input: 'Is it maybe light?', expected: false },
  { input: 'Could the answer be paint?', expected: true },
  { input: 'does it have wood in it?', expected: false },
  { input: 'is it a kind of building?', expected: false },
  { input: 'What about an apartment complex?', expected: true },
  { input: 'Is it just a building?', expected: false },
  { input: 'The secret word must surely be house.', expected: true },
  { input: 'is it abstract?', expected: false },
  { input: 'is it a natural phenomenon?', expected: false },
  { input: 'can you measure it?', expected: false },
  { input: 'is it a number?', expected: false },
  { input: 'Is it clock?', expected: true },
  { input: 'Could it be a day?', expected: true },
  { input: 'The answer must be time.', expected: true },
  { input: 'is it a natural phenomenon?', expected: false },
  { input: 'is it made from water?', expected: false },
  { input: 'Could it perhaps be snow?', expected: true },
  { input: 'I think it\'s a cloud, maybe?', expected: true },
  { input: 'Hmm, I suspect it is probably rain.', expected: true },
  { input: 'can it fly?', expected: false },
  { input: 'is it used in baseball?', expected: false },
  { input: 'I think it might be a ball?', expected: true },
  { input: 'Could it be a vampire?', expected: true },
  { input: 'Could the word be bat?', expected: true },
  { input: 'is it a kind of profession?', expected: false },
  { input: 'do they chase the bad guys?', expected: false },
  { input: 'Could it be a nurse?', expected: true },
  { input: 'I wonder if it\'s a surgeon?', expected: true },
  { input: 'It has to be a doctor.', expected: true },
  { input: 'is it part of the body?', expected: false },
  { input: 'Could I guess hand?', expected: true },
  { input: 'Probably toe?', expected: true },
  { input: 'After thinking long and hard, I bet the answer is feet!', expected: true },
  { input: 'is it a beverage?', expected: false },
  { input: 'is it a place?', expected: false },
  { input: 'Could it be a restaurant?', expected: true },
  { input: 'I am quite sure the answer is café.', expected: true },
  { input: 'is it food?', expected: false },
  { input: 'can you hold it', expected: false },
  { input: 'Is it pasta?', expected: true },
  { input: 'Could it be bread?', expected: true },
  { input: 'Is it... pizza!?', expected: true }
];

describe('Check if a message is a guess', function() {
  cases.forEach(({ input, expected }) => {
    it(`result for "${input}" should be "${expected}"`, async function() {
      const type = await isMessageGuess(input);
      expect(type).to.equal(expected);
    });
  });
});