import 'server-only';

import { tool } from "@langchain/core/tools";
import { getNetwork } from "@teesa-monorepo/nft/src/networks";
import { z } from "zod";

export const nftDetails = tool(
  async () => {
    console.log("TOOL: nftDetails");

    const network = getNetwork();

    return `
The NFTs are generated by Teesa as a reward for the winner of the game.
The NFTs are stored on the ${network.displayName} network.
There is a link to the NFT collection on OpenSea in the menu.
    `;
  },
  {
    name: "nftDetails",
    description: "Get the details for the NFT collection",
    schema: z.object({})
  }
);