export const INITIAL_MESSAGE = "INITIAL_MESSAGE";
export const WON_GAME_MESSAGE = 'WON_GAME_MESSAGE';
export const PRIZE_AWARDED_MESSAGE = 'PRIZE_AWARDED_MESSAGE_';
export const TEESA_WALLET_INSUFFICIENT_FUNDS_MESSAGE = 'TEESA_WALLET_INSUFFICIENT_FUNDS_MESSAGE';
export const PROCESSING_ERROR_MESSAGE = 'PROCESSING_ERROR_MESSAGE';