name: Release tag

on:
  release:
    types:
      - published

jobs:
  release-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get job html url
        id: get_job_html_url
        uses: actions/github-script@v7
        with:
          script: |
            const { data: workflow_run } =
              await github.rest.actions.listJobsForWorkflowRunAttempt({
                attempt_number: process.env.GITHUB_RUN_ATTEMPT,
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.runId,
              });
            const job_html_url = workflow_run.jobs[0].html_url;
            return job_html_url;

      - name: Replace placeholders in app-manifest.json
        run: |
          AAPP_CNAME=$(echo "${{ github.event.release.tag_name }}" | tr -d '.')
          echo "AAPP_CNAME=$AAPP_CNAME" >> $GITHUB_ENV

          sed -i "s/__AAPPTAG__/${{ github.event.release.tag_name }}/g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s/__AAPPCNAME__/$AAPP_CNAME/g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPDEVPUBKEY__#${{ secrets.AAPP_DEV_PUB_KEY }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"

          sed -i "s#__AAPPBUILDARGCLOUDVOLUMEPATH__#${{ vars.AAPPBUILDARGCLOUDVOLUMEPATH }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGOLLAMAMODEL__#${{ vars.AAPPBUILDARGOLLAMAMODEL }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGOPENROUTERAPIKEY__#${{ secrets.AAPPBUILDARGOPENROUTERAPIKEY }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGOPENROUTERMODEL__#${{ vars.AAPPBUILDARGOPENROUTERMODEL }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGPRIVYIOAPPID__#${{ secrets.AAPPBUILDARGPRIVYIOAPPID }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGPRIVYIOAPPSECRET__#${{ secrets.AAPPBUILDARGPRIVYIOAPPSECRET }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGATTESTATIONURL__#${{ vars.AAPPBUILDARGATTESTATIONURL }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"  
          sed -i "s#__AAPPBUILDARGTWITTERUSERNAME__#${{ vars.AAPPBUILDARGTWITTERUSERNAME }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGTWITTERPASSWORD__#${{ secrets.AAPPBUILDARGTWITTERPASSWORD }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGTWITTEREMAIL__#${{ vars.AAPPBUILDARGTWITTEREMAIL }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGTWITTER2FASECRET__#${{ secrets.AAPPBUILDARGTWITTER2FASECRET }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGTWITTERINTERACTIONMONITORINGINTERVALSECONDS__#${{ vars.AAPPBUILDARGTWITTERINTERACTIONMONITORINGINTERVALSECONDS }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGTWITTERPOSTINGINTERVALMINMINUTES__#${{ vars.AAPPBUILDARGTWITTERPOSTINGINTERVALMINMINUTES }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGTWITTERPOSTINGINTERVALMAXMINUTES__#${{ vars.AAPPBUILDARGTWITTERPOSTINGINTERVALMAXMINUTES }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGINITIALWALLETPRIVATEKEY__#${{ secrets.AAPPBUILDARGINITIALWALLETPRIVATEKEY }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGCONTRACTNETWORK__#${{ vars.AAPPBUILDARGCONTRACTNETWORK }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGRPCURL__#${{ secrets.AAPPBUILDARGRPCURL }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGBLOCKCHAINSCANAPIKEY__#${{ secrets.AAPPBUILDARGBLOCKCHAINSCANAPIKEY }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGTEAMADDRESS__#${{ vars.AAPPBUILDARGTEAMADDRESS }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGPINATAAPIKEY__#${{ secrets.AAPPBUILDARGPINATAAPIKEY }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGPINATAAPISECRET__#${{ secrets.AAPPBUILDARGPINATAAPISECRET }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGFALAIAPIKEY__#${{ secrets.AAPPBUILDARGFALAIAPIKEY }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGNFTCONTRACTADDRESS__#${{ vars.AAPPBUILDARGNFTCONTRACTADDRESS }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          
          cat "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"

      - name: Deploy confidential virtual machine in Azure
        uses: comrade-coop/aapp-toolkit/workflow@main
        with:
          client_id: ${{ secrets.AZURE_CLIENT_ID }}
          client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          resource_group: "teesa"
          vm_name: "teesa-${{ env.AAPP_CNAME }}"
          vm_disk_size: "30"
          vm_network_id: ${{ secrets.AZURE_VM_NETWORK_ID }}
          vm_ssh_enabled: "false"
          vm_dev_key: ${{ secrets.AZURE_VM_SSH_KEY }}
          aapp_manifest: "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          certbot_email: "dev-gen2@teesa.ai"
          current_job_url: ${{ steps.get_job_html_url.outputs.result }}