name: Release tag

on:
  release:
    types:
      - published

jobs:
  release-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get job html url
        id: get_job_html_url
        uses: actions/github-script@v7
        with:
          script: |
            const { data: workflow_run } =
              await github.rest.actions.listJobsForWorkflowRunAttempt({
                attempt_number: process.env.GITHUB_RUN_ATTEMPT,
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.runId,
              });
            const job_html_url = workflow_run.jobs[0].html_url;
            return job_html_url;

      - name: Replace placeholders in app-manifest.json
        run: |
          AAPP_CNAME=$(echo "${{ github.event.release.tag_name }}" | sed 's/[^0-9]//g' | awk '{printf "v%04d", $0}')
          echo "AAPP_CNAME=$AAPP_CNAME" >> $GITHUB_ENV

          sed -i "s/__AAPPTAG__/${{ github.event.release.tag_name }}/g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s/__AAPPCNAME__/$AAPP_CNAME/g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPDEVPUBKEY__#${{ secrets.AAPP_DEV_PUB_KEY }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"

          sed -i "s#__AAPPBUILDARGNETWORK__#${{ vars.AAPPBUILDARGNETWORK }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGRPCURL__#${{ secrets.AAPPBUILDARGRPCURL }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGBLOCKCHAINSCANAPIKEY__#${{ secrets.AAPPBUILDARGBLOCKCHAINSCANAPIKEY }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGTEAMADDRESS__#${{ vars.AAPPBUILDARGTEAMADDRESS }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGANTHROPICAPIKEY__#${{ secrets.AAPPBUILDARGANTHROPICAPIKEY }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGPRIVYIOAPPID__#${{ secrets.AAPPBUILDARGPRIVYIOAPPID }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGPRIVYIOAPPSECRET__#${{ secrets.AAPPBUILDARGPRIVYIOAPPSECRET }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGELIZAAPIURL__#${{ vars.AAPPBUILDARGELIZAAPIURL }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGELIZAAGENTID__#${{ secrets.AAPPBUILDARGELIZAAGENTID }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGATTESTATIONURL__#${{ vars.AAPPBUILDARGATTESTATIONURL }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          sed -i "s#__AAPPBUILDARGLANGCHAINTRACINGV2__#${{ vars.AAPPBUILDARGLANGCHAINTRACINGV2 }}#g" "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"

          cat "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"

      - name: Deploy confidential virtual machine in Azure
        uses: comrade-coop/aapp-toolkit/workflow@main
        with:
          client_id: ${{ secrets.AZURE_CLIENT_ID }}
          client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          resource_group: "teesa"
          vm_name: "teesa-${{ env.AAPP_CNAME }}"
          vm_disk_size: "30"
          vm_network_id: ${{ secrets.AZURE_VM_NETWORK_ID }}
          vm_ssh_enabled: "false"
          vm_dev_key: ${{ secrets.AZURE_VM_SSH_KEY }}
          aapp_manifest: "${GITHUB_WORKSPACE}/.github/workflows/app-manifest.json"
          certbot_email: "dev@teesa.ai"
          current_job_url: ${{ steps.get_job_html_url.outputs.result }}
