name: Update redirects

on:
  workflow_dispatch:

jobs:
  release-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          api_location: .github/workflows/landing-site/api
          config_file_location: .github/workflows/landing-site
          skip_app_build: true
